/**
 * 资产台账系统错误码枚举
 * @version v1.4
 *
 * 单一来源：docs/design/asset-ledger-error-codes.md（第 4 节）
 */
export const ErrorCode = {
  // ========== Web 层（AUTH_* / CONFIG_*）==========
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  CONFIG_INVALID_REQUEST: 'CONFIG_INVALID_REQUEST',
  CONFIG_LEDGER_FIELD_KEY_INVALID: 'CONFIG_LEDGER_FIELD_KEY_INVALID',
  CONFIG_LEDGER_FIELD_ASSET_TYPE_MISMATCH: 'CONFIG_LEDGER_FIELD_ASSET_TYPE_MISMATCH',
  CONFIG_LEDGER_FIELD_VALUE_INVALID: 'CONFIG_LEDGER_FIELD_VALUE_INVALID',
  CONFIG_LEDGER_FIELD_LIMIT_EXCEEDED: 'CONFIG_LEDGER_FIELD_LIMIT_EXCEEDED',
  CONFIG_INVALID_TIMEZONE: 'CONFIG_INVALID_TIMEZONE',
  CONFIG_INVALID_HHMM: 'CONFIG_INVALID_HHMM',
  CONFIG_SOURCE_NOT_FOUND: 'CONFIG_SOURCE_NOT_FOUND',
  CONFIG_CREDENTIAL_NOT_FOUND: 'CONFIG_CREDENTIAL_NOT_FOUND',
  CONFIG_AGENT_NOT_FOUND: 'CONFIG_AGENT_NOT_FOUND',
  CONFIG_RUN_NOT_FOUND: 'CONFIG_RUN_NOT_FOUND',
  CONFIG_ASSET_NOT_FOUND: 'CONFIG_ASSET_NOT_FOUND',
  CONFIG_ASSET_MERGE_ASSET_TYPE_MISMATCH: 'CONFIG_ASSET_MERGE_ASSET_TYPE_MISMATCH',
  CONFIG_ASSET_MERGE_CYCLE_DETECTED: 'CONFIG_ASSET_MERGE_CYCLE_DETECTED',
  CONFIG_ASSET_MERGE_VM_REQUIRES_OFFLINE: 'CONFIG_ASSET_MERGE_VM_REQUIRES_OFFLINE',
  CONFIG_SOURCE_RECORD_NOT_FOUND: 'CONFIG_SOURCE_RECORD_NOT_FOUND',
  CONFIG_PREFERENCE_NOT_FOUND: 'CONFIG_PREFERENCE_NOT_FOUND',
  CONFIG_EXPORT_NOT_FOUND: 'CONFIG_EXPORT_NOT_FOUND',
  CONFIG_EXPORT_EXPIRED: 'CONFIG_EXPORT_EXPIRED',
  CONFIG_SCHEDULE_GROUP_NOT_FOUND: 'CONFIG_SCHEDULE_GROUP_NOT_FOUND',
  CONFIG_DUPLICATE_CANDIDATE_NOT_FOUND: 'CONFIG_DUPLICATE_CANDIDATE_NOT_FOUND',
  CONFIG_SIGNAL_LINK_NOT_FOUND: 'CONFIG_SIGNAL_LINK_NOT_FOUND',
  CONFIG_DUPLICATE_NAME: 'CONFIG_DUPLICATE_NAME',
  CONFIG_RESOURCE_CONFLICT: 'CONFIG_RESOURCE_CONFLICT',

  // ========== Worker 层（PLUGIN_* / SCHEMA_* / DB_*）==========
  PLUGIN_EXEC_FAILED: 'PLUGIN_EXEC_FAILED',
  PLUGIN_TIMEOUT: 'PLUGIN_TIMEOUT',
  PLUGIN_EXIT_NONZERO: 'PLUGIN_EXIT_NONZERO',
  PLUGIN_OUTPUT_INVALID_JSON: 'PLUGIN_OUTPUT_INVALID_JSON',
  PLUGIN_SCHEMA_VERSION_UNSUPPORTED: 'PLUGIN_SCHEMA_VERSION_UNSUPPORTED',
  PLUGIN_RESPONSE_INVALID: 'PLUGIN_RESPONSE_INVALID',

  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  INVENTORY_INCOMPLETE: 'INVENTORY_INCOMPLETE',
  INVENTORY_RELATIONS_EMPTY: 'INVENTORY_RELATIONS_EMPTY',
  RAW_PERSIST_FAILED: 'RAW_PERSIST_FAILED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
  DB_READ_FAILED: 'DB_READ_FAILED',

  // ========== 插件层（VCENTER_*）==========
  VCENTER_CONFIG_INVALID: 'VCENTER_CONFIG_INVALID',
  VCENTER_AUTH_FAILED: 'VCENTER_AUTH_FAILED',
  VCENTER_PERMISSION_DENIED: 'VCENTER_PERMISSION_DENIED',
  VCENTER_NETWORK_ERROR: 'VCENTER_NETWORK_ERROR',
  VCENTER_TLS_ERROR: 'VCENTER_TLS_ERROR',
  VCENTER_RATE_LIMIT: 'VCENTER_RATE_LIMIT',
  VCENTER_PARSE_ERROR: 'VCENTER_PARSE_ERROR',
  VCENTER_API_VERSION_UNSUPPORTED: 'VCENTER_API_VERSION_UNSUPPORTED',
  VCENTER_HOST_DETAIL_NOT_FOUND: 'VCENTER_HOST_DETAIL_NOT_FOUND',

  // ========== 插件层（PVE_* / HYPERV_* / ALIYUN_* / PHYSICAL_*）==========
  PVE_CONFIG_INVALID: 'PVE_CONFIG_INVALID',
  PVE_AUTH_FAILED: 'PVE_AUTH_FAILED',
  PVE_PERMISSION_DENIED: 'PVE_PERMISSION_DENIED',
  PVE_NETWORK_ERROR: 'PVE_NETWORK_ERROR',
  PVE_TLS_ERROR: 'PVE_TLS_ERROR',
  PVE_RATE_LIMIT: 'PVE_RATE_LIMIT',
  PVE_PARSE_ERROR: 'PVE_PARSE_ERROR',

  HYPERV_CONFIG_INVALID: 'HYPERV_CONFIG_INVALID',
  HYPERV_AUTH_FAILED: 'HYPERV_AUTH_FAILED',
  HYPERV_PERMISSION_DENIED: 'HYPERV_PERMISSION_DENIED',
  HYPERV_NETWORK_ERROR: 'HYPERV_NETWORK_ERROR',
  HYPERV_TLS_ERROR: 'HYPERV_TLS_ERROR',
  HYPERV_PARSE_ERROR: 'HYPERV_PARSE_ERROR',

  ALIYUN_CONFIG_INVALID: 'ALIYUN_CONFIG_INVALID',
  ALIYUN_AUTH_FAILED: 'ALIYUN_AUTH_FAILED',
  ALIYUN_PERMISSION_DENIED: 'ALIYUN_PERMISSION_DENIED',
  ALIYUN_NETWORK_ERROR: 'ALIYUN_NETWORK_ERROR',
  ALIYUN_RATE_LIMIT: 'ALIYUN_RATE_LIMIT',
  ALIYUN_PARSE_ERROR: 'ALIYUN_PARSE_ERROR',

  PHYSICAL_CONFIG_INVALID: 'PHYSICAL_CONFIG_INVALID',
  PHYSICAL_AUTH_FAILED: 'PHYSICAL_AUTH_FAILED',
  PHYSICAL_PERMISSION_DENIED: 'PHYSICAL_PERMISSION_DENIED',
  PHYSICAL_NETWORK_ERROR: 'PHYSICAL_NETWORK_ERROR',
  PHYSICAL_TLS_ERROR: 'PHYSICAL_TLS_ERROR',
  PHYSICAL_PARSE_ERROR: 'PHYSICAL_PARSE_ERROR',

  // ========== 插件层（SOLARWINDS_*）==========
  SOLARWINDS_CONFIG_INVALID: 'SOLARWINDS_CONFIG_INVALID',
  SOLARWINDS_AUTH_FAILED: 'SOLARWINDS_AUTH_FAILED',
  SOLARWINDS_PERMISSION_DENIED: 'SOLARWINDS_PERMISSION_DENIED',
  SOLARWINDS_NETWORK_ERROR: 'SOLARWINDS_NETWORK_ERROR',
  SOLARWINDS_TLS_ERROR: 'SOLARWINDS_TLS_ERROR',
  SOLARWINDS_RATE_LIMIT: 'SOLARWINDS_RATE_LIMIT',
  SOLARWINDS_PARSE_ERROR: 'SOLARWINDS_PARSE_ERROR',

  // ========== 通用（INTERNAL_*）==========
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_NOT_IMPLEMENTED: 'INTERNAL_NOT_IMPLEMENTED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
