/**
 * 资产台账系统错误码枚举
 * @version v1.0
 *
 * 单一来源：docs/design/asset-ledger-error-codes.md（第 4 节）
 */
export const ErrorCode = {
  // ========== Web 层（AUTH_* / CONFIG_*）==========
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  CONFIG_INVALID_REQUEST: 'CONFIG_INVALID_REQUEST',
  CONFIG_INVALID_TIMEZONE: 'CONFIG_INVALID_TIMEZONE',
  CONFIG_INVALID_HHMM: 'CONFIG_INVALID_HHMM',
  CONFIG_SOURCE_NOT_FOUND: 'CONFIG_SOURCE_NOT_FOUND',
  CONFIG_CREDENTIAL_NOT_FOUND: 'CONFIG_CREDENTIAL_NOT_FOUND',
  CONFIG_RUN_NOT_FOUND: 'CONFIG_RUN_NOT_FOUND',
  CONFIG_ASSET_NOT_FOUND: 'CONFIG_ASSET_NOT_FOUND',
  CONFIG_SOURCE_RECORD_NOT_FOUND: 'CONFIG_SOURCE_RECORD_NOT_FOUND',
  CONFIG_SCHEDULE_GROUP_NOT_FOUND: 'CONFIG_SCHEDULE_GROUP_NOT_FOUND',
  CONFIG_DUPLICATE_NAME: 'CONFIG_DUPLICATE_NAME',
  CONFIG_RESOURCE_CONFLICT: 'CONFIG_RESOURCE_CONFLICT',

  // ========== Worker 层（PLUGIN_* / SCHEMA_* / DB_*）==========
  PLUGIN_EXEC_FAILED: 'PLUGIN_EXEC_FAILED',
  PLUGIN_TIMEOUT: 'PLUGIN_TIMEOUT',
  PLUGIN_EXIT_NONZERO: 'PLUGIN_EXIT_NONZERO',
  PLUGIN_OUTPUT_INVALID_JSON: 'PLUGIN_OUTPUT_INVALID_JSON',
  PLUGIN_SCHEMA_VERSION_UNSUPPORTED: 'PLUGIN_SCHEMA_VERSION_UNSUPPORTED',
  PLUGIN_RESPONSE_INVALID: 'PLUGIN_RESPONSE_INVALID',

  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  INVENTORY_INCOMPLETE: 'INVENTORY_INCOMPLETE',
  RAW_PERSIST_FAILED: 'RAW_PERSIST_FAILED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
  DB_READ_FAILED: 'DB_READ_FAILED',

  // ========== 插件层（VCENTER_*）==========
  VCENTER_CONFIG_INVALID: 'VCENTER_CONFIG_INVALID',
  VCENTER_AUTH_FAILED: 'VCENTER_AUTH_FAILED',
  VCENTER_PERMISSION_DENIED: 'VCENTER_PERMISSION_DENIED',
  VCENTER_NETWORK_ERROR: 'VCENTER_NETWORK_ERROR',
  VCENTER_TLS_ERROR: 'VCENTER_TLS_ERROR',
  VCENTER_RATE_LIMIT: 'VCENTER_RATE_LIMIT',
  VCENTER_PARSE_ERROR: 'VCENTER_PARSE_ERROR',
  VCENTER_API_VERSION_UNSUPPORTED: 'VCENTER_API_VERSION_UNSUPPORTED',

  // ========== 通用（INTERNAL_*）==========
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_NOT_IMPLEMENTED: 'INTERNAL_NOT_IMPLEMENTED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
